runtime: nodejs20
service: notes-shafa

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /
    static_dir: build