steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'frontend'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/frontend-shafa'
      - '--build-arg'
      - 'REACT_APP_API_URL=${__API_URL}'
      - '.'
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend-shafa']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'frontend-shafa'
      - '--image'
      - 'gcr.io/$PROJECT_ID/frontend-shafa'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/frontend-shafa'

options:
  logging: CLOUD_LOGGING_ONLY
